/* ════════════════════════════════════════
   OpenQuiz — Download & HTML Generation
   ════════════════════════════════════════ */

function getQuizData(){
  const qs=builderState.questions.filter(q=>q.question&&q.options.filter(Boolean).length===4);
  return {
    title:document.getElementById('f-title').value.trim()||'My Quiz',
    subject:document.getElementById('f-subject').value.trim(),
    chapter:document.getElementById('f-chapter').value.trim(),
    topic:document.getElementById('f-topic').value.trim(),
    description:document.getElementById('f-desc').value.trim(),
    timerSeconds:parseInt(document.getElementById('f-timer').value)||30,
    author:document.getElementById('f-author').value.trim(),
    icon:builderState.icon,
    colorScheme:builderState.colorScheme,
    backdropData:builderState.backdropData,
    questions:qs
  };
}

function downloadQuizHTML(){
  const data=getQuizData();
  if(!data.title){toast('⚠️ Add a title first','err');return;}
  if(data.questions.length===0){toast('⚠️ Add at least one complete question','err');return;}
  generateAndDownloadHTML(data);
}

async function downloadQuizHTMLById(id){
  const quizzes=await getAllQuizzes();
  const q=quizzes.find(q=>q.id===id);
  if(q) generateAndDownloadHTML(q);
}

function generateAndDownloadHTML(data){
  const html=buildSelfQuizHTML(data);
  const blob=new Blob([html],{type:'text/html;charset=utf-8'});
  const a=document.createElement('a');
  a.href=URL.createObjectURL(blob);
  a.download=(data.title||'quiz').replace(/[^a-z0-9]/gi,'-').toLowerCase()+'.html';
  a.click();
  URL.revokeObjectURL(a.href);
  toast('⬇️ Quiz downloaded!','ok');
}

function buildSelfQuizHTML(data){
  const scheme=SCHEME_HEADERS[data.colorScheme]||SCHEME_HEADERS.purple;
  const jsonData=JSON.stringify({
    title:data.title,subject:data.subject,chapter:data.chapter,
    topic:data.topic,description:data.description,author:data.author,
    timerSeconds:data.timerSeconds,icon:data.icon,colorScheme:data.colorScheme,
    questions:data.questions
  },null,2);
  const bannerStyle=data.backdropData
    ?`background-image:url('${data.backdropData}');background-size:cover;background-position:center;`
    :`background:${scheme};`;
  const questionsJS=JSON.stringify(data.questions.map(q=>({
    question:q.question,
    options:q.options,
    correct:q.correct,
    explanation:q.explanation||'',
    difficulty:q.difficulty||'easy',
    referenceTags:q.tags||[]
  })));

return `<!DOCTYPE html>
<!--
  Generated by OpenQuiz — https://openquiz.selfstudy.xyz
  ${data.title}${data.author?' · '+data.author:''}
  Questions: ${data.questions.length} · Timer: ${data.timerSeconds}s
-->
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(data.title)} — OpenQuiz</title>
<meta name="theme-color" content="#2563eb"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css"/>
<script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.js"><\/script>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans+Bengali:wght@400;500;600;700&display=swap');
:root{--primary:#2563eb;--primary-hover:#1d4ed8;--primary-light:#e8f0fe;--primary-glow:rgba(37,99,235,.15);--accent:#0ea472;--bg:#f4f6f9;--bg-elevated:#fff;--card:#fff;--card-hover:#f8fafc;--text:#1a2235;--text-secondary:#5a6a85;--muted:#64748b;--border:#dde3ed;--border-strong:#cbd5e1;--shadow-sm:0 1px 3px rgba(30,50,100,.07);--shadow:0 4px 12px rgba(30,50,100,.09),0 2px 4px rgba(30,50,100,.05);--header-grad:${scheme};--correct:#16a34a;--correct-bg:#dcfce7;--wrong:#dc2626;--wrong-bg:#fee2e2;--warning:#d97706;--warning-bg:#fef9c3;--hover-bg:#eef1f6;--explain-bg:#eef3ff;--explain-border:#2563eb;--explain-text:#1e3a6b;--tracker-bg:#e8f0fe;--tracker-text:#2563eb;--score-bg:#d1fae5;--score-text:#065f46;--radius-sm:6px;--radius-md:9px;--radius-lg:14px;--transition-fast:.15s ease;--transition:.25s ease}
body.dark{--primary:#5b9cf6;--primary-hover:#7db3f8;--primary-light:rgba(91,156,246,.14);--bg:#1c1f26;--bg-elevated:#252930;--card:#252930;--card-hover:#2f333d;--text:#e8ecf4;--text-secondary:#9aa3b8;--muted:#64748b;--border:#3a3f4c;--border-strong:#475569;--header-grad:${scheme};--correct:#4ade80;--correct-bg:rgba(22,163,74,.15);--wrong:#f87171;--wrong-bg:rgba(220,38,38,.15);--warning:#fbbf24;--warning-bg:rgba(217,119,6,.15);--hover-bg:#2f333d;--explain-bg:rgba(37,99,235,.1);--explain-border:#5b9cf6;--explain-text:#a8c4f0;--tracker-bg:rgba(91,156,246,.14);--tracker-text:#5b9cf6;--score-bg:rgba(74,222,128,.15);--score-text:#4ade80}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}
body{font-family:'Inter','Noto Sans Bengali',Arial,sans-serif;background:var(--bg);color:var(--text);min-height:100vh;line-height:1.6;font-size:15px;transition:background .25s,color .25s;-webkit-font-smoothing:antialiased}
a{color:var(--primary);text-decoration:none}button{font-family:inherit;cursor:pointer;border:none;outline:none;transition:all var(--transition-fast)}
::selection{background:var(--primary);color:#fff}.hidden{display:none!important}
.container{max-width:600px;margin:0 auto;padding:0 16px}
.dark-btn{background:var(--hover-bg);border:1.5px solid var(--border);color:var(--text-secondary);padding:6px 13px;border-radius:var(--radius-md);font-size:12px;cursor:pointer;white-space:nowrap;transition:all .2s;box-shadow:var(--shadow-sm)}
.dark-btn:hover{background:var(--border);color:var(--text)}
.start-screen{position:fixed;inset:0;z-index:300;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:16px;background:var(--bg);transition:opacity .35s,transform .35s;overflow-y:auto}
.start-screen.hide{opacity:0;transform:scale(1.03);pointer-events:none}
.start-card{background:var(--card);border:1px solid var(--border);border-radius:var(--radius-lg);padding:24px 20px 18px;width:100%;max-width:380px;text-align:center;position:relative;box-shadow:var(--shadow-sm);${data.backdropData?`background-image:url('${data.backdropData}');background-size:cover;background-position:center;overflow:hidden;`:''}
}
${data.backdropData?'.start-card::before{content:"";position:absolute;inset:0;background:rgba(0,0,0,.45);border-radius:var(--radius-lg)}.start-card>*{position:relative;z-index:1}.start-card .start-title,.start-card .start-sub,.start-card .start-qcount{color:#fff !important}.start-card .start-badge{background:rgba(255,255,255,.15) !important;color:#fff !important;border-color:rgba(255,255,255,.3) !important}.start-card .info-chip{background:rgba(255,255,255,.15) !important;border-color:rgba(255,255,255,.2) !important}.start-card .info-chip .chip-val{color:#fff !important}.start-card .info-chip .chip-label{color:rgba(255,255,255,.7) !important}':''}
.start-icon{font-size:28px;line-height:1;margin-bottom:6px}
.start-qcount{font-size:12px;font-weight:700;color:var(--muted);margin:2px 0 4px}
.start-badge{display:inline-flex;align-items:center;font-size:9px;letter-spacing:1.2px;color:var(--primary);text-transform:uppercase;background:var(--tracker-bg);border:1px solid var(--explain-border);border-radius:99px;padding:2px 10px;margin-bottom:8px}
.start-title{font-size:clamp(15px,3.5vw,20px);font-weight:700;color:var(--text);line-height:1.3;margin-bottom:4px}
.start-sub{color:var(--text-secondary);font-size:12px;line-height:1.5;margin-bottom:14px}
.start-info-row{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-bottom:14px}
.info-chip{display:flex;flex-direction:column;align-items:center;background:var(--hover-bg);border:1px solid var(--border);border-radius:var(--radius-sm);padding:5px 12px;min-width:60px}
.info-chip .chip-val{font-size:15px;font-weight:700;color:var(--primary)}
.info-chip .chip-label{font-size:8px;color:var(--text-secondary);letter-spacing:.6px;text-transform:uppercase}
.start-btn{width:100%;background:var(--primary);border:none;border-radius:var(--radius-md);padding:10px 20px;font-size:14px;font-weight:600;color:#fff;cursor:pointer}
.start-btn:hover{background:var(--primary-hover)}
.quiz-wrapper{width:100%;max-width:600px;margin:0 auto;display:flex;flex-direction:column;min-height:100vh;padding:24px 16px}
.quiz-container{background:var(--card);border-radius:var(--radius-lg);box-shadow:var(--shadow-sm);overflow:hidden}
.quiz-header{background:var(--header-grad);padding:12px 16px 0;color:#fff}
.quiz-header-top{display:flex;justify-content:space-between;align-items:center}
.quiz-header-title{font-size:17px;font-weight:700;color:#fff;line-height:1.3;margin:8px 0 0}
.quiz-header-location{font-size:10px;font-weight:500;color:rgba(255,255,255,.65);margin:1px 0 0}
.progress-wrap{background:rgba(255,255,255,.2);height:5px;margin-top:10px;border-radius:3px}
.progress-bar{height:100%;background:#facc15;transition:width .45s}
.card-body-quiz{padding:24px 24px 22px}
.meta-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}
.question-tracker{background:var(--tracker-bg);color:var(--tracker-text);font-size:13px;font-weight:700;padding:5px 13px;border-radius:20px}
.score-badge{background:var(--score-bg);color:var(--score-text);font-size:13px;font-weight:700;padding:5px 13px;border-radius:20px}
.timer-wrap{position:relative;width:46px;height:46px;flex-shrink:0}
.timer-wrap svg{transform:rotate(-90deg);width:46px;height:46px}
.timer-track{fill:none;stroke:var(--border);stroke-width:4}
.timer-fill{fill:none;stroke:var(--primary);stroke-width:4;stroke-linecap:round;stroke-dasharray:113.1;stroke-dashoffset:0;transition:stroke-dashoffset 1s linear,stroke .4s}
.timer-fill.warn{stroke:var(--wrong)}
.timer-num{position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:13px;font-weight:700;color:var(--primary)}
.timer-num.warn{color:var(--wrong)}
.question-text{font-size:20px;font-weight:700;margin-bottom:18px;line-height:1.5;color:var(--text)}
.options-container{display:grid;grid-template-columns:1fr 1fr;gap:11px}
@media(max-width:480px){.options-container{grid-template-columns:1fr}}
.option-btn{background:var(--card);border:2px solid var(--border);border-radius:var(--radius-md);padding:12px 14px;font-size:15px;text-align:left;cursor:pointer;transition:background .22s,border-color .22s,transform .12s,box-shadow .18s;color:var(--text);display:flex;align-items:center;gap:11px;min-height:54px}
.option-btn:nth-child(1){border-left:4px solid #e53935}.option-btn:nth-child(2){border-left:4px solid #1e88e5}
.option-btn:nth-child(3){border-left:4px solid #43a047}.option-btn:nth-child(4){border-left:4px solid #fb8c00}
.opt-label{display:inline-flex;align-items:center;justify-content:center;width:30px;height:30px;min-width:30px;border-radius:50%;font-size:13px;font-weight:700;flex-shrink:0}
.option-btn:nth-child(1) .opt-label{background:#fde8e8;color:#c62828}.option-btn:nth-child(2) .opt-label{background:#e3f0fb;color:#1565c0}
.option-btn:nth-child(3) .opt-label{background:#e8f5e9;color:#2e7d32}.option-btn:nth-child(4) .opt-label{background:#fff3e0;color:#e65100}
body.dark .option-btn:nth-child(1) .opt-label{background:#3b1a1a;color:#ef9a9a}body.dark .option-btn:nth-child(2) .opt-label{background:#152536;color:#90caf9}
body.dark .option-btn:nth-child(3) .opt-label{background:#1a2e1a;color:#a5d6a7}body.dark .option-btn:nth-child(4) .opt-label{background:#2e2010;color:#ffcc80}
.option-btn:hover:not(:disabled){background:var(--hover-bg);transform:translateY(-2px);box-shadow:0 4px 14px rgba(0,0,0,.12)}
.option-btn:disabled{cursor:not-allowed}
.option-btn.correct{background:var(--correct-bg)!important;border-color:var(--correct)!important}
.option-btn.correct .opt-label{background:var(--correct)!important;color:#fff!important}
.option-btn.wrong{background:var(--wrong-bg)!important;border-color:var(--wrong)!important}
.option-btn.wrong .opt-label{background:var(--wrong)!important;color:#fff!important}
.explanation-box{display:none;margin-top:16px;background:var(--explain-bg);border-left:4px solid var(--explain-border);border-radius:0 8px 8px 0;padding:13px 15px}
.explanation-box.show{display:block}
.ex-title{font-size:13px;font-weight:700;color:var(--primary);margin-bottom:6px}
.ex-text{font-size:15px;line-height:1.65;color:var(--explain-text)}
.footer-controls{display:flex;justify-content:space-between;align-items:center;margin-top:22px}
.timeout-msg{font-size:13px;color:var(--wrong);font-weight:600;display:none}
.timeout-msg.show{display:block}
.next-btn{background:var(--primary);color:#fff;border:none;padding:12px 26px;font-size:17px;border-radius:8px;cursor:pointer;display:none;font-weight:700;margin-left:auto}
.next-btn.show{display:block}
.next-btn:hover{background:var(--primary-hover);transform:translateY(-1px)}
.result-stats-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:12px}
.result-stat{background:var(--card);border:1.5px solid var(--border);border-radius:10px;padding:8px 6px;text-align:center}
.stat-icon{font-size:16px;margin-bottom:2px}.stat-value{font-size:16px;font-weight:800;color:var(--text)}.stat-label{font-size:10px;color:var(--muted);font-weight:600}
.correct-stat{border-color:var(--correct)}.correct-stat .stat-value{color:var(--correct)}
.wrong-stat{border-color:var(--wrong)}.wrong-stat .stat-value{color:var(--wrong)}
.timeout-stat{border-color:var(--warning)}.timeout-stat .stat-value{color:var(--warning)}
.result-actions{display:flex;gap:8px;justify-content:center;flex-wrap:wrap;margin-bottom:16px}
.result-review-section{text-align:left;margin-top:4px;border-top:1.5px solid var(--border);padding-top:12px}
.review-header h4{font-size:15px;font-weight:800;color:var(--text);margin-bottom:10px}
.review-filter-group{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:12px}
.review-filter-btn{padding:5px 10px;border-radius:99px;font-size:11px;font-weight:700;border:1.5px solid var(--border);background:var(--card);color:var(--muted);cursor:pointer;transition:all .2s}
.review-filter-btn:hover{border-color:var(--primary);color:var(--text)}
.review-filter-btn.active-all{background:var(--primary);color:#fff;border-color:var(--primary)}
.review-filter-btn.active-correct{background:var(--correct);color:#fff;border-color:var(--correct)}
.review-filter-btn.active-wrong{background:var(--wrong);color:#fff;border-color:var(--wrong)}
.review-filter-btn.active-timeout{background:var(--warning);color:#fff;border-color:var(--warning)}
.review-card{background:var(--card);border:1.5px solid var(--border);border-radius:10px;padding:12px;margin-bottom:8px}
.review-card.correct{border-left:3px solid var(--correct)}.review-card.wrong{border-left:3px solid var(--wrong)}.review-card.timeout{border-left:3px solid var(--warning)}
.review-card-header{display:flex;align-items:center;gap:6px;margin-bottom:6px;flex-wrap:wrap}
.review-q-number{font-size:11px;font-weight:800;background:var(--hover-bg);padding:2px 8px;border-radius:5px}
.review-status{font-size:10px;font-weight:700;padding:2px 8px;border-radius:99px}
.review-status-correct{background:var(--correct-bg);color:var(--correct)}.review-status-wrong{background:var(--wrong-bg);color:var(--wrong)}.review-status-timeout{background:var(--warning-bg);color:var(--warning)}
.review-time{font-size:11px;color:var(--muted);margin-left:auto}
.review-question{font-size:14px;font-weight:700;margin-bottom:8px;line-height:1.5;color:var(--text)}
.review-options{display:flex;flex-direction:column;gap:4px;margin-bottom:6px}
.review-option{display:flex;align-items:center;gap:8px;padding:7px 10px;border-radius:8px;border:1.5px solid var(--border);font-size:13px;background:var(--card)}
.review-option.review-correct{background:var(--correct-bg);border-color:var(--correct)}.review-option.review-wrong{background:var(--wrong-bg);border-color:var(--wrong)}.review-option.review-selected-correct{background:var(--correct-bg);border-color:var(--correct)}
.review-opt-label{display:inline-flex;align-items:center;justify-content:center;width:26px;height:26px;min-width:26px;border-radius:50%;font-size:12px;font-weight:700;background:var(--hover-bg);color:var(--text);flex-shrink:0}
.review-correct .review-opt-label{background:var(--correct);color:#fff}.review-wrong .review-opt-label{background:var(--wrong);color:#fff}.review-selected-correct .review-opt-label{background:var(--correct);color:#fff}
.review-opt-text{flex:1;min-width:0}.review-opt-marker{font-weight:800;font-size:16px;flex-shrink:0}
.review-explanation{background:var(--explain-bg);border-left:3px solid var(--explain-border);border-radius:0 8px 8px 0;padding:8px 12px;margin-top:4px}
.review-ex-title{font-size:11px;font-weight:700;color:var(--primary);margin-bottom:3px}.review-ex-text{font-size:13px;line-height:1.5;color:var(--explain-text)}
.restart-btn{background:var(--primary);color:#fff;border:none;padding:9px 22px;font-size:14px;border-radius:8px;cursor:pointer;font-weight:700}
.restart-btn:hover{background:var(--primary-hover)}
.quit-btn{padding:6px 14px;border-radius:8px;font-size:12px;font-weight:700;background:rgba(255,255,255,.12);color:rgba(255,255,255,.8);border:1px solid rgba(255,255,255,.2);cursor:pointer;transition:all .2s;white-space:nowrap;display:inline-flex;align-items:center;gap:5px}
.quit-btn:hover{background:rgba(239,68,68,.8);color:#fff;border-color:rgba(239,68,68,.8)}
.modal-overlay{position:fixed;inset:0;background:rgba(0,0,0,.65);z-index:500;display:none;align-items:center;justify-content:center;padding:16px;backdrop-filter:blur(4px)}
.modal-overlay.show{display:flex}
.modal-box{background:var(--card);border:1px solid var(--border);border-radius:var(--radius-lg);padding:24px;max-width:360px;width:100%;text-align:center}
.modal-box h3{font-size:18px;font-weight:800;margin-bottom:8px}.modal-box p{font-size:14px;color:var(--text-secondary);margin-bottom:20px}
.modal-btns{display:flex;gap:10px;justify-content:center}
.modal-btn{padding:9px 22px;border-radius:8px;font-size:14px;font-weight:700;cursor:pointer;border:none}
.modal-btn-cancel{background:var(--hover-bg);color:var(--text)}.modal-btn-confirm{background:var(--wrong);color:#fff}
@keyframes fadeUp{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}
.anim-fade-up{animation:fadeUp .4s ease}
.site-footer{border-top:1px solid var(--border);padding:16px;text-align:center;margin-top:auto}
.footer-copy{font-size:11px;color:var(--muted)}
@media(max-width:480px){.result-stats-grid{grid-template-columns:repeat(2,1fr)}.quiz-wrapper{padding:12px 8px}.card-body-quiz{padding:16px}}
.json-copy-fab{position:fixed;bottom:18px;left:18px;z-index:400;background:var(--card);border:1.5px solid var(--border);color:var(--text-secondary);padding:7px 13px;border-radius:10px;font-size:11px;font-weight:700;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.2);transition:all .2s;display:flex;align-items:center;gap:5px}
.json-copy-fab:hover{background:var(--primary);color:#fff;border-color:var(--primary)}
</style>
</head>
<body>

<button class="json-copy-fab" onclick="copyQuizJSON()" title="Copy quiz JSON">
  📋 Copy JSON
</button>

<div class="start-screen" id="startScreen">
  <div class="start-card">
    <button class="dark-btn" style="position:absolute;top:8px;right:8px;padding:3px 8px;font-size:10px" onclick="toggleDark()">🌙</button>
    <div class="start-icon">${data.icon||'📝'}</div>
    <div class="start-badge" id="startBadge">MCQ</div>
    <div class="start-title" id="startTitle">Loading...</div>
    <div class="start-qcount" id="startQcount"></div>
    <div class="start-sub" id="startSub"></div>
    <div class="start-info-row">
      <div class="info-chip"><span class="chip-val" id="chipQuestions">—</span><span class="chip-label">QUESTIONS</span></div>
      <div class="info-chip"><span class="chip-val" id="chipTime">—</span><span class="chip-label">TIME/Q</span></div>
    </div>
    <button class="start-btn" id="startBtn">🚀 Start Quiz</button>
  </div>
</div>

<div class="quiz-wrapper hidden" id="quizWrapper">
  <div class="quiz-container">
    <div class="quiz-header" id="quizHeader">
      <div class="quiz-header-top">
        <span style="font-size:11px;font-weight:600;color:rgba(255,255,255,.8)">OpenQuiz</span>
        <button class="quit-btn" onclick="quitQuiz()">✕ Quit</button>
      </div>
      <h2 class="quiz-header-title" id="quizHeaderTitle">Quiz</h2>
      <p class="quiz-header-location" id="quizHeaderLocation"></p>
      <div class="progress-wrap"><div class="progress-bar" id="progressBar"></div></div>
    </div>
    <div class="card-body-quiz">
      <div id="quizContent">
        <div class="meta-row">
          <div class="question-tracker" id="tracker">—</div>
          <div style="display:flex;align-items:center;gap:10px">
            <div class="score-badge" id="scoreBadge">✅ Score: 0</div>
            <div class="timer-wrap">
              <svg viewBox="0 0 46 46"><circle class="timer-track" cx="23" cy="23" r="18"/><circle class="timer-fill" id="timerFill" cx="23" cy="23" r="18"/></svg>
              <div class="timer-num" id="timerNum">—</div>
            </div>
          </div>
        </div>
        <div class="question-text" id="questionText"></div>
        <div class="options-container" id="optionsContainer"></div>
        <div class="explanation-box" id="explanationBox">
          <div class="ex-title">💡 Explanation</div>
          <div class="ex-text" id="explanationText"></div>
        </div>
        <div class="footer-controls">
          <div class="timeout-msg" id="timeoutMsg">⏱ Time's up!</div>
          <button class="next-btn" id="nextBtn" onclick="nextQuestion()">Next ❯</button>
        </div>
      </div>
      <div id="resultBox" style="display:none"></div>
    </div>
  </div>
  <footer class="site-footer">
    <div class="footer-copy">${getSetting('footer','Made with OpenQuiz · Self Study')}</div>
  </footer>
</div>

<div class="modal-overlay" id="quitModal">
  <div class="modal-box">
    <h3>Quit Quiz?</h3>
    <p>Your progress will be lost.</p>
    <div class="modal-btns">
      <button class="modal-btn modal-btn-cancel" onclick="hideQuitModal()">Continue</button>
      <button class="modal-btn modal-btn-confirm" onclick="confirmQuit()">Quit</button>
    </div>
  </div>
</div>

<script>
const QUIZ_CONFIG={title:${JSON.stringify(data.title)},subject:${JSON.stringify(data.subject||'')},chapter:${JSON.stringify(data.chapter||'')},topic:${JSON.stringify(data.topic||'')},description:${JSON.stringify(data.description||'')},timerSeconds:${data.timerSeconds||30}};
const QUESTIONS=${questionsJS};
const QUIZ_JSON=${JSON.stringify(jsonData)};

function copyQuizJSON(){
  navigator.clipboard.writeText(QUIZ_JSON).then(()=>{
    const btn=document.querySelector('.json-copy-fab');
    const orig=btn.innerHTML;
    btn.innerHTML='✅ Copied!';
    btn.style.background='var(--correct)';btn.style.color='#fff';
    setTimeout(()=>{btn.innerHTML=orig;btn.style.background='';btn.style.color='';},2000);
  }).catch(()=>alert('Copy failed. Please copy manually.'));
}

const state={currentIndex:0,score:0,correctCount:0,wrongCount:0,timeoutCount:0,totalQuestions:0,totalTimeTaken:0,timerInterval:null,questionStartTime:0,results:[],shuffled:[]};

function $(id){return document.getElementById(id)}
function toggleDark(){document.body.classList.toggle('dark');const b=$('startScreen').querySelector('.dark-btn');if(b)b.textContent=document.body.classList.contains('dark')?'☀️':'🌙';}
function initQuiz(){
  state.shuffled=[...QUESTIONS];
  state.totalQuestions=state.shuffled.length;
  $('startTitle').textContent=QUIZ_CONFIG.title;
  $('startQcount').textContent=QUIZ_CONFIG.subject+(QUIZ_CONFIG.chapter?' · '+QUIZ_CONFIG.chapter:'');
  $('startSub').textContent=QUIZ_CONFIG.description||'';
  $('chipQuestions').textContent=state.totalQuestions;
  $('chipTime').textContent=QUIZ_CONFIG.timerSeconds+'s';
  $('startBtn').onclick=startQuiz;
}
function startQuiz(){
  state.currentIndex=0;state.score=0;state.correctCount=0;state.wrongCount=0;state.timeoutCount=0;state.totalTimeTaken=0;state.results=[];
  const ss=$('startScreen');
  ss.classList.add('hide');
  setTimeout(()=>{ss.classList.add('hidden');$('quizWrapper').classList.remove('hidden');},350);
  $('quizHeaderTitle').textContent=QUIZ_CONFIG.title;
  $('quizHeaderLocation').textContent=[QUIZ_CONFIG.subject,QUIZ_CONFIG.chapter,QUIZ_CONFIG.topic].filter(Boolean).join(' · ');
  loadQuestion();
}
function loadQuestion(){
  if(state.currentIndex>=state.totalQuestions){showResult();return;}
  const q=state.shuffled[state.currentIndex];
  const pct=((state.currentIndex)/state.totalQuestions)*100;
  $('progressBar').style.width=pct+'%';
  $('tracker').textContent='Q '+(state.currentIndex+1)+' / '+state.totalQuestions;
  $('scoreBadge').textContent='✅ Score: '+state.score;
  $('questionText').textContent=q.question;
  $('explanationBox').classList.remove('show');
  $('timeoutMsg').classList.remove('show');
  $('nextBtn').classList.remove('show');
  const labels=['A','B','C','D'];
  $('optionsContainer').innerHTML=q.options.map((o,i)=>\`<button class="option-btn" onclick="selectOption(\${i})"><span class="opt-label">\${labels[i]}</span>\${o}</button>\`).join('');
  startTimer(QUIZ_CONFIG.timerSeconds,q);
  state.questionStartTime=Date.now();
}
function startTimer(secs,q){
  if(state.timerInterval)clearInterval(state.timerInterval);
  let remaining=secs;
  const fill=$('timerFill');const num=$('timerNum');
  const circ=113.1;
  function tick(){
    remaining--;
    const offset=circ*(1-remaining/secs);
    fill.style.strokeDashoffset=offset;
    num.textContent=remaining;
    const warn=remaining<=5;
    fill.classList.toggle('warn',warn);num.classList.toggle('warn',warn);
    if(remaining<=0){clearInterval(state.timerInterval);onTimeout(q);}
  }
  fill.style.strokeDashoffset=0;num.textContent=secs;fill.classList.remove('warn');num.classList.remove('warn');
  state.timerInterval=setInterval(tick,1000);
}
function onTimeout(q){
  $('timeoutMsg').classList.add('show');$('nextBtn').classList.add('show');$('nextBtn').textContent='Next ❯';
  document.querySelectorAll('.option-btn').forEach(b=>b.disabled=true);
  document.querySelectorAll('.option-btn')[q.correct]?.classList.add('correct');
  if(q.explanation){$('explanationText').textContent=q.explanation;$('explanationBox').classList.add('show');}
  state.timeoutCount++;state.totalTimeTaken+=QUIZ_CONFIG.timerSeconds;
  state.results.push({question:q.question,options:q.options,correct:q.correct,selected:-1,isCorrect:false,isTimeout:true,timeTaken:QUIZ_CONFIG.timerSeconds,explanation:q.explanation||''});
}
function selectOption(oi){
  clearInterval(state.timerInterval);
  const timeTaken=Math.round((Date.now()-state.questionStartTime)/1000);
  const q=state.shuffled[state.currentIndex];
  const btns=document.querySelectorAll('.option-btn');
  btns.forEach(b=>b.disabled=true);
  const isCorrect=oi===q.correct;
  btns[oi].classList.add(isCorrect?'correct':'wrong');
  if(!isCorrect)btns[q.correct].classList.add('correct');
  if(isCorrect){state.score+=10;state.correctCount++;}else state.wrongCount++;
  state.totalTimeTaken+=timeTaken;
  if(q.explanation){$('explanationText').textContent=q.explanation;$('explanationBox').classList.add('show');}
  $('nextBtn').classList.add('show');
  $('nextBtn').textContent=state.currentIndex===state.totalQuestions-1?'See Results 🎉':'Next ❯';
  state.results.push({question:q.question,options:q.options,correct:q.correct,selected:oi,isCorrect,isTimeout:false,timeTaken,explanation:q.explanation||''});
}
function nextQuestion(){state.currentIndex++;loadQuestion();}
function showResult(){
  $('quizContent').style.display='none';$('resultBox').style.display='block';
  const pct=state.totalQuestions>0?Math.round((state.correctCount/state.totalQuestions)*100):0;
  const avgTime=state.totalQuestions>0?Math.round(state.totalTimeTaken/state.totalQuestions):0;
  let gc='var(--correct)',gl='Great!';
  if(pct<40){gc='var(--wrong)';gl='Keep Practicing';}else if(pct<70){gc='var(--warning)';gl='Good Effort';}
  let rev='';
  state.results.forEach((r,i)=>{
    const sc=r.isTimeout?'timeout':(r.isCorrect?'correct':'wrong');
    const sl=r.isTimeout?'⏱ Timeout':(r.isCorrect?'✅ Correct':'❌ Wrong');
    const sbc=r.isTimeout?'review-status-timeout':(r.isCorrect?'review-status-correct':'review-status-wrong');
    let opts='';
    r.options.forEach((o,oi)=>{
      let cls='',mk='';
      if(oi===r.correct&&oi===r.selected){cls='review-selected-correct';mk='✓';}
      else if(oi===r.correct){cls='review-correct';mk='✓';}
      else if(oi===r.selected){cls='review-wrong';mk='✗';}
      opts+=\`<div class="review-option \${cls}"><span class="review-opt-label">\${'ABCD'[oi]}</span><span class="review-opt-text">\${o}</span>\${mk?\`<span class="review-opt-marker">\${mk}</span>\`:''}</div>\`;
    });
    rev+=\`<div class="review-card \${sc} anim-fade-up" style="animation-delay:\${i*.05}s">
      <div class="review-card-header"><span class="review-q-number">Q\${i+1}</span><span class="review-status \${sbc}">\${sl}</span><span class="review-time">\${r.timeTaken}s</span></div>
      <div class="review-question">\${r.question}</div>
      <div class="review-options">\${opts}</div>
      \${r.explanation?\`<div class="review-explanation"><div class="review-ex-title">💡 Explanation</div><div class="review-ex-text">\${r.explanation}</div></div>\`:''}
    </div>\`;
  });
  $('resultBox').innerHTML=\`
    <div style="text-align:center;padding:10px 0 8px">
      <div style="margin-bottom:12px"><span style="font-size:14px;font-weight:800;padding:3px 14px;border-radius:99px;background:\${gc}20;color:\${gc}">\${pct}% — \${gl}</span></div>
      <div class="result-stats-grid">
        <div class="result-stat correct-stat"><div class="stat-icon">✅</div><div class="stat-value">\${state.correctCount}</div><div class="stat-label">Correct</div></div>
        <div class="result-stat wrong-stat"><div class="stat-icon">❌</div><div class="stat-value">\${state.wrongCount}</div><div class="stat-label">Wrong</div></div>
        <div class="result-stat timeout-stat"><div class="stat-icon">⏱</div><div class="stat-value">\${state.timeoutCount}</div><div class="stat-label">Timeout</div></div>
        <div class="result-stat" style="border-color:var(--primary)"><div class="stat-icon">🎯</div><div class="stat-value" style="color:var(--primary)">\${state.score}</div><div class="stat-label">Score</div></div>
        <div class="result-stat" style="border-color:var(--muted)"><div class="stat-icon">⏱</div><div class="stat-value">\${avgTime}s</div><div class="stat-label">Avg Time</div></div>
        <div class="result-stat" style="border-color:var(--muted)"><div class="stat-icon">📊</div><div class="stat-value">\${state.totalQuestions}</div><div class="stat-label">Total</div></div>
      </div>
      <div class="result-actions"><button class="restart-btn" onclick="restartQuiz()">🔄 Restart Quiz</button></div>
      <div class="result-review-section">
        <div class="review-header"><h4>📋 Review All Questions</h4></div>
        <div class="review-filter-group">
          <button class="review-filter-btn active-all" data-f="all" onclick="setFilter('all')">📋 All (\${state.totalQuestions})</button>
          <button class="review-filter-btn" data-f="correct" onclick="setFilter('correct')">✅ Correct (\${state.correctCount})</button>
          <button class="review-filter-btn" data-f="wrong" onclick="setFilter('wrong')">❌ Wrong (\${state.wrongCount})</button>
          <button class="review-filter-btn" data-f="timeout" onclick="setFilter('timeout')">⏱ Timeout (\${state.timeoutCount})</button>
        </div>
        <div id="reviewCards">\${rev}</div>
      </div>
    </div>\`;
}
function setFilter(f){
  document.querySelectorAll('.review-filter-btn').forEach(b=>{b.className='review-filter-btn';if(b.dataset.f===f)b.classList.add('active-'+f);});
  document.querySelectorAll('.review-card').forEach(c=>{c.style.display=(f==='all'||c.classList.contains(f))?'block':'none';});
}
function restartQuiz(){$('quizContent').style.display='block';$('resultBox').style.display='none';$('resultBox').innerHTML='';initQuiz();$('startBtn').click();}
function quitQuiz(){$('quitModal').classList.add('show');}
function hideQuitModal(){$('quitModal').classList.remove('show');}
function confirmQuit(){
  clearInterval(state.timerInterval);hideQuitModal();
  $('startScreen').classList.remove('hidden','hide');$('startScreen').style.display='';$('quizWrapper').classList.add('hidden');
  $('quizContent').style.display='block';$('resultBox').style.display='none';
}
document.addEventListener('DOMContentLoaded',initQuiz);
<\/script>
</body>
</html>`;
}
